/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Logic.Configuration;
import Logic.FileManager;
import Logic.Globals;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** @author Ana Elena Ulate Salas
 ** @date 2017-08-01
 ** 
 **/
public class StartGameView extends javax.swing.JFrame {
    Configuration configuration;
    ArrayList<Configuration> config;
    /**
     * Creates new form StartGameView
     */ 
    public StartGameView() {
        initComponents();
        setLocationRelativeTo(null);
        loadConfig();
    }
    //Load view for start game
    public static void starGameWindow()
    {
        GameView game = new GameView();
        game.setVisible(true);
    }
    public void SaveToTxt(){
        configuration = new Configuration(nickNameTextField.getText(), Integer.parseInt(rowsComboBox.getSelectedItem().toString()), Integer.parseInt(columnsComboBox.getSelectedItem().toString()));
        FileManager file = new FileManager();
        String storage = file.readTextFile("gameconfig.txt");
        file.writeTextFile("gameconfig.txt", storage + configuration);
        loadConfig();
    }
    public void loadConfig() {
        FileManager file = new FileManager();
        String data = file.readTextFile("gameconfig.txt");
        String[] aux = data.split("\n");
        if (!data.trim().equals("")) {
            config = new ArrayList<>(aux.length);
            for (int i = 0; i < aux.length; i++) {
                String[] temp = aux[i].split(",");
                Configuration c = new Configuration();
                c.setNickname(temp[0]);
                c.setRows(Integer.parseInt(temp[1].trim()));
                c.setColumns(Integer.parseInt(temp[2].trim()));
                config.add(c);
                System.out.println(c.getNickname());
                System.out.println(c.getRows());
                System.out.println(c.getColumns());
            }
        }
    }
    //Method to select stars icons
    public void selectAnt() {
        switch (starsSlider.getValue()) 
        {
            case 1:
                String pathOneStar = "/Icons/oneStar.png";
                URL urlOneStar = this.getClass().getResource(pathOneStar);
                ImageIcon oneStarIcon = new ImageIcon(urlOneStar);
                showStarsLabel.setIcon(oneStarIcon);
                break;
            case 2:
                String pathTwo = "/Icons/twoStars.jpg";
                URL twoUrl = this.getClass().getResource(pathTwo);
                ImageIcon iconNumberTwo = new ImageIcon(twoUrl);
                showStarsLabel.setIcon(iconNumberTwo);
                break;
            case 3:
                String pathThreeStar = "/Icons/threeStars.jpg";
                URL ThreeStar = this.getClass().getResource(pathThreeStar);
                ImageIcon threeStarIcon = new ImageIcon(ThreeStar);
                showStarsLabel.setIcon(threeStarIcon);
                break;
            case 4:
                String pathFourtStar = "/Icons/fourtStars.jpg";
                URL urlFourtStar = this.getClass().getResource(pathFourtStar);
                ImageIcon fourtStarIcon = new ImageIcon(urlFourtStar);
                showStarsLabel.setIcon(fourtStarIcon);
                break;
            case 5:
                String pathFiveStar = "/Icons/fiveStars.jpg";
                URL urlFiveStar = this.getClass().getResource(pathFiveStar);
                ImageIcon fiveStarIcon = new ImageIcon(urlFiveStar);
                showStarsLabel.setIcon(fiveStarIcon);
                break;
            default:
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        starsSlider = new javax.swing.JSlider();
        showStarsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nickNameTextField = new javax.swing.JTextField();
        startGameButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rowsComboBox = new javax.swing.JComboBox<>();
        columnsComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        clodsComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(673, 499));
        setMinimumSize(new java.awt.Dimension(673, 499));
        setPreferredSize(new java.awt.Dimension(673, 499));
        getContentPane().setLayout(null);

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));
        principalPanel.setOpaque(false);

        starsSlider.setBackground(new java.awt.Color(0, 153, 153));
        starsSlider.setForeground(new java.awt.Color(255, 255, 255));
        starsSlider.setMajorTickSpacing(1);
        starsSlider.setMaximum(5);
        starsSlider.setMinimum(1);
        starsSlider.setPaintLabels(true);
        starsSlider.setPaintTicks(true);
        starsSlider.setValue(1);
        starsSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                starsSliderStateChanged(evt);
            }
        });

        showStarsLabel.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NickName:");

        startGameButton.setBackground(new java.awt.Color(0, 153, 153));
        startGameButton.setForeground(new java.awt.Color(255, 255, 255));
        startGameButton.setText("GOO");
        startGameButton.setFocusable(false);
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rows");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Columns");

        rowsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        columnsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rows");

        clodsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6" }));

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(starsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nickNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(61, 61, 61)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(principalPanelLayout.createSequentialGroup()
                                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(principalPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rowsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(principalPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(columnsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)
                                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(clodsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(showStarsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nickNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rowsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(columnsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clodsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addComponent(showStarsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(starsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        getContentPane().add(principalPanel);
        principalPanel.setBounds(0, 0, 670, 500);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fondoPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 670, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void starsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_starsSliderStateChanged
    }//GEN-LAST:event_starsSliderStateChanged
    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        Globals.amountRows = Integer.parseInt((String)this.rowsComboBox.getSelectedItem());
        Globals.amountColumns = Integer.parseInt((String) this.columnsComboBox.getSelectedItem());
        SaveToTxt();
        starGameWindow();
        this.setVisible(false);
    }//GEN-LAST:event_startGameButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGameView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> clodsComboBox;
    private javax.swing.JComboBox<String> columnsComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nickNameTextField;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JComboBox<String> rowsComboBox;
    private javax.swing.JLabel showStarsLabel;
    private javax.swing.JSlider starsSlider;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables
}